# Experiments and cases
[experiment_1]
folder = "experiment_1"
cases = ["AT_Hintereisferner", "CH_Aletschgletscher", "NO_Vestisen"]

[experiment_2]
folder = "experiment_2"
cases = ["CL_NPI", "PK_Baltoro", "RU_FJL"]

# Path to individual glacier datasets

# experiment 1
["CH_Aletschgletscher"]
ref_dem_path = "CH_Aletsch_Copernicus_REF_DEM.tif"
rgi_path = "11_rgi60_ceu_wgs84_utm32n.shp"
selected_path = "11_rgi60_ceu_wgs84_utm32n_ale_selection.shp"
tdx_path = "TDX_DEM_crp/*dem_mcf.tif"
aster_path = "DEM*tif"
validation_dates = ["2011-09-13", "2017-09-21"]

["AT_Hintereisferner"]
ref_dem_path = "AT_Hintereis_Copernicus_REF_DEM.tif"
rgi_path = "11_rgi60_ceu_wgs84_utm32n.shp"
selected_path = "11_rgi60_ceu_wgs84_utm32n_hef_selection.shp"
tdx_path = "TDX_DEM_crp/*dem_mcf.tif"
aster_path = "Hinterheis/ASTER_DEM_Used_only/DEM*tif"
validation_dates = ["2010-10-08", "2019-09-21"]

["NO_Vestisen"]
ref_dem_path = "NO_Vestisen_Copernicus_REF_DEM.tif"
rgi_path = "08_rgi60_sca_wgs84_utmn33.shp"
selected_path = "08_rgi60_sca_wgs84_utmn33_ves_selection.shp"
tdx_path = "*dem_mcf.tif"
aster_path = "DEM*tif"
validation_dates = ["2008-09-02", "2020-08-10"]

# experiment 2
["PK_Baltoro"]
ref_dem_path = "PK_Baltoro_Copernicus_REF_DEM.tif"
rgi_path = "14_rgi60_asw_wgs84_utm43n.shp"
selected_path = "14_rgi60_asw_wgs84_utm43n_baltoro_selection.shp"
tdx_path = "*dem_mcf.tif"
aster_path = "DEM*tif"
validation_dates = ["2000-02-01", "2012-10-01", "2019-10-01"]

["RU_FJL"]
ref_dem_path = "RU_FJL_Copernicus_REF_DEM_30m.tif"
rgi_path = "09_rgi60_rua_wgs83_utm40n.shp"
selected_path = "09_rgi60_rua_wgs83_utm40n_fjl_selection.shp"
tdx_path = "*dem_mcf.tif"
aster_path = "DEM*tif"
validation_dates = ["2010-12-01", "2017-12-01"]

["CL_NPI"]
ref_dem_path = "CL_NPI_Copernicus_REF_DEM.tif"
rgi_path = "17_rgi60_san_wgs84_utm18s.shp"
selected_path = "17_rgi60_san_wgs84_utm18s_SAN_NPI_selection.shp"
tdx_path = "*dem_mcf.tif"
aster_path = "ASTER_DEM_Used_only/DEM*tif"
validation_dates = ["2000-02-01", "2014-03-01", "2019-03-01"]


